config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'posts/new' => 'posts#new'

  post 'posts/create' => 'posts#create', as: :posts

  get 'signup' => 'users#new'
  post 'signup' => 'users#create', as: :users

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title,
  presence: :true,
  :length => 6..20

  validates :link,
  presence: :true,
  :url => true


end

app/models/user.rb
 class User < ActiveRecord::Base

  has_secure_password

  attr_reader :email

  validates :email,
  presence: true,
  uniqueness: { case_sensitive: false },
  email_format: { message: "doesn't look like an email address" },
  on: :create

  validates :name,
  presence: true,
  length: { maximum: 20 },
  on: :create

  has_many :posts

  def self.authenticate email,password
    User.find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user, :get_users



  def current_user
    # the user_id is crucial because regular :id won't work
    @current_user ||= User.find_by_id(session[:user_id])
  end


  def get_users
    @users = User.all
    # binding.pry
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # before_action :current_user


  def index
    # binding.pry
  end

  def set_user
    # @user =
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    # :user_id = @current_user.id
  end

  def create
    params[:post][:user_id] = @current_user.id
    @post = Post.create post_params
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :link, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # render plain: 'new session'
  end

  def create
    @user= User.authenticate(params[:user][:email],
      params[:user][:password])
    # binding.pry

    if @user
      # binding.pry
      session[:user_id] = @user.id
      # binding.pry
      flash[:success] = 'You are now logged in.'
      redirect_to root_path
    else
      # binding.pry
      flash[:danger]= 'Invalid email or password'

      redirect_to login_path
    end
  end

    def destroy
      session[:user_id] = nil
      flash[:info] = 'You are logged out.'
      redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    # this doesn't have to do anything but reroute
    @user = User.new
  end

  def create
    @user = User.create user_params
    # binding.pry
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkBoard</title>

  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="navbar">
      <div class="row pull-right">
      <div class='row'>
        <div class="pull-right">
          <% if @current_user %>
            <%= 'You are logged in as' %>
            <%= @current_user.email %> |
            <%= link_to 'logout', logout_path %>
          <% else %>
            <%= link_to 'signup', signup_path %> |
            <%= link_to 'login', login_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <%= yield %>

</div>



</body>
</html>

app/views/main/index.html.erb
<h1>Hello!!!!</h1>
<%= render 'shared/flash' %>

<div class='row'>
  <div class="pull-right">
    <% if @current_user %>
      <%= 'You are logged in as' %>
      <%= @current_user.email %> |
      <%= link_to 'logout', logout_path %>
    <% else %>
      <%= link_to 'signup', signup_path %> |
      <%= link_to 'login', login_path %>
    <% end %>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
  <h1>Posts</h1>
  <%= link_to '', posts_new_path, class: 'btn btn-default glyphicon glyphicon-plus pull-right' %>
</div>

<%= render 'shared/flash' %>


<% @posts.each do |p| %>
<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
  <div class="well well-sm">
  <h2><%= p.title %></h2>
  <a href=<%= p.link %>><h3><%= p.link %></h3></a>
  <h3>Posted by <%= @users.find_by_id(p.user_id).email %></h3>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_for @post do |f| %>
<%= f.text_field :title %>
<%= f.text_field :link %>
<%= @post.user_id = @current_user.id %>
<%= f.submit %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class=<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">


    <h1>Users#new</h1>
    <p>Find me in app/views/users/new.html.erb</p>
    <%= render 'shared/flash' %>
    <%= form_for @user do |f| %>
      <%= f.text_field :email, placeholder: "Enter your email" %>
      <%= f.text_field :name, placeholder: "Enter your username" %>
      <%= f.password_field :password, placeholder: "Enter a password" %>
      <%= f.submit %>
    <% end %>
    </div>
</div>